### ISSUE TITLE
Add daily one-time refreshing mechanism for newsfeed

### ISSUE THREAD

**Issue by wsloth** [wsloth/Index#7]
One of the features I really want for this app is a mechanism where the news-feed is only refreshed once a day. The aim is to provide a great newspaper-like Hacker News reading experience, 

In short, these are the requirements:
- Automatically refresh the newsfeed once a day when opening the app, between 7am and 10pm (device time)
- When refreshing, store a bit of state that notes the app has already been refreshed for today
- Until the next fresh day, no refresh will be done. So the newsfeed of that day will have to be stored (just the list of newsfeed article ID's should be enough -- the rest can be fetched from the API)
- Timestamp of refresh becomes the edition number: `Thursday, 12 September, 17:45 Edition`

Nice to have:
- A manual refresh setting somewhere for the real addicts. Maybe first with a popup informing of the time until next edition, asking the user to have patience.
- Allow the user to view the feed in their preferred way. I usually read Hacker news using https://hckrnews.com/ , where I use the "Top 50%" filter.

**Comment by agent515** [comment]
@wsloth I would like to take up this issue.

**Comment by wsloth** [comment]
Hi @agent515, thanks for taking interest. Feel free to pick up this new feature!
