### ISSUE TITLE
Build an introduction onboarding screen for new app users

### ISSUE THREAD

**Issue by wsloth** [wsloth/Index#9]
I've got a general vision where I want this app to be a Hacker News client which makes you read a bit less - by providing you with an updated newsfeed only once a day. The general UI has already been designed by me, but there's tons of room for new features.

If you are interested in tipping your toes in Flutter development, let me know what you want to do! I'm a beginner with Flutter as well, and would love to collaborate on this.

**Comment by wsloth** [comment]
Hey @ShivamMenda, thanks for taking interest! I think a scrollable onboarding screen would be really cool, but the downside is that the app is right now really dumb and without a lot of features to highlight 😄  What would you want the onboarding screen to show? Perhaps introduce the general vision of the app: "Designed to make you engage less and learn more", or something.

**Comment by ShivamMenda** [comment]
@wsloth Will work on it asap.Thanks.
